version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8004:5000
    volumes:
      - .:/app
    depends_on:
      - db
      

  db:
    image: mysql:5.7.32
    restart: always
    environment:
      MYSQL_DATABASE: likes
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33063:3306

      